apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpcds-trino-tester
  namespace: testing-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino-tester
  template:
    metadata:
      labels:
        app: trino-tester
    spec:
      containers:
      - name: trino-tester
        image: frenoid/trino-load-tester:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: MODE
            value: "tpcds" # Creates tables using Trino
          - name: TRINO_HOST
            value: "trino.trino.svc.cluster.local" # Host of Trino cluster
          - name: TRINO_PORT
            value: "8080"
          - name: TRINO_USER
            value: "trino-tester" # Trino connection user
          - name: TRINO_CATALOG
            value: "tpcds" # tpcds catalog
          - name: TPCDS_SCHEMA
            value: "sf100" # Size of tpcds data
          - name: SLEEP_INTERVAL
            value: "2" # Seconds to wait between interations
          - name: MAX_RETRY
            value: "3" # Maximum no of retries before giving up
          - name: TPCDS_QUERY_NUMBER
            value: "0" # Pick query to repeat, 0 means iterate through all
          - name: TPCDS_SKIP_NUMBERS
            value: "14" # comma separated list of numbers to skip e.g. 10,15,21
          
          

